# Generated by Django 4.1.13

import attendance.mapping
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    引入「占位账号排除严格度」，并校正两个默认口径。

    ⚠️ 本文件的 help_text 必须与 attendance/models.py 保持一致，否则
       `makemigrations --check` 会报仍需生成迁移。改模型的 help_text 时，
       记得同步改这里（或另生成一个 AlterField 迁移）。
    """

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerule',
            name='exclude_mode',
            field=models.CharField(choices=[('no_dept', '严格：考勤组命中且无部门（推荐）'), ('no_dept_no', '最严格：考勤组命中且无部门且无工号'), ('group_only', '宽松：考勤组命中即排除（会误伤真人）'), ('name_only', '仅按姓名名单')], default='no_dept', help_text='⚠️ 不要选「考勤组命中即排除」：该考勤组里有真实员工，会被误伤', max_length=20, verbose_name='占位账号排除严格度'),
        ),
        migrations.AlterField(
            model_name='attendancerule',
            name='exclude_if_no_data',
            field=models.BooleanField(default=False, help_text='⚠️ 默认关闭。实测真实员工可能整月无打卡（产假、长期出差、高管不打卡），基线报表里这些人是保留的，排除会让月报漏人', verbose_name='排除全月无数据的人'),
        ),
        migrations.AlterField(
            model_name='attendancerule',
            name='clamp_negative_overtime',
            field=models.BooleanField(default=True, help_text='单日加班 = max(0, (工作时长-标准时长)/60)。桌面版不截断，负加班会冲减月度合计', verbose_name='负加班截断为 0'),
        ),
        migrations.AlterField(
            model_name='attendancerule',
            name='excluded_attend_groups',
            field=models.JSONField(blank=True, default=attendance.mapping.default_excluded_attend_groups, help_text='⚠️ 不是"见到这个考勤组就排除"！还要同时满足下面的"无信息"条件。实测该考勤组里混着真实员工（有部门、有真实出勤）', verbose_name='占位账号的考勤组'),
        ),
        migrations.AlterField(
            model_name='attendancerule',
            name='excluded_employees',
            field=models.JSONField(blank=True, default=attendance.mapping.default_excluded_employees, help_text='按姓名排除的补充名单。主判据是下面的结构化规则；真实员工姓名不要写进代码，需要时在此页填写', verbose_name='排除人员名单'),
        ),
    ]
